package com.spring.security.core.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

@ApiModel(value="com.spring.security.core.domain.itemCategory")
public class itemCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_category.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="id")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_category.cat
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cat商品类别")
    private String cat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_category.created_at
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="createdAt创建时间")
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_category.id
     *
     * @return the value of item_category.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_category.id
     *
     * @param id the value for item_category.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_category.cat
     *
     * @return the value of item_category.cat
     *
     * @mbg.generated
     */
    public String getCat() {
        return cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_category.cat
     *
     * @param cat the value for item_category.cat
     *
     * @mbg.generated
     */
    public void setCat(String cat) {
        this.cat = cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_category.created_at
     *
     * @return the value of item_category.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_category.created_at
     *
     * @param createdAt the value for item_category.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cat=").append(cat);
        sb.append(", createdAt=").append(createdAt);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        itemCategory other = (itemCategory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCat() == null ? other.getCat() == null : this.getCat().equals(other.getCat()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCat() == null) ? 0 : getCat().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        return result;
    }
}