package com.spring.security.core.dao;

import com.spring.security.core.domain.ItemCategory;
import com.spring.security.core.domain.ItemCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    long countByExample(ItemCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int deleteByExample(ItemCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int insert(ItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int insertSelective(ItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    List<ItemCategory> selectByExample(ItemCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    ItemCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ItemCategory record, @Param("example") ItemCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ItemCategory record, @Param("example") ItemCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemCategory record);
}