package com.spring.security.core.dao;

import com.spring.security.core.domain.itemCategory;
import com.spring.security.core.domain.itemCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface itemCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    long countByExample(itemCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int deleteByExample(itemCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int insert(itemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int insertSelective(itemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    List<itemCategory> selectByExample(itemCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    itemCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") itemCategory record, @Param("example") itemCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") itemCategory record, @Param("example") itemCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(itemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(itemCategory record);
}